version: '2.1'
jobs:
  build:
    docker:
      - image: cimg/node:16.14-browsers
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: echo "export IMAGE_TAG=${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}" >> workspace/image_tag
      - persist_to_workspace:
          root: workspace
          paths:
            - image_tag
  deploy:
    docker:
      - image: 'cimg/python:3.9.1'
    steps:
      - attach_workspace:
          at: ./workspace
      - run: cat ./workspace/image_tag >> $BASH_ENV
      - run: echo ${IMAGE_TAG}
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
