version: 2.1
orbs:
  node-gql-mongo: nextmoov/node-gql-mongo@1.0.5
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
      - image: circleci/mongo:4.4
        environment:
          MONGO_USERNAME: mongouser
          MONGO_PASSWORD: mongopass
    steps:
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - checkout
      - run:
          name: Connect to DB
          command: mongo localhost --eval "printjson(db.apikeys.count());" 
